# Generated by Django 3.0.11 on 2020-12-05 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_auto_20201205_1508'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickevent',
            name='short_url',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shortener.ShortUrl'),
        ),
    ]
